server:
  port: 80
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://local:61611
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic